name: Monitor Releases

on:
  schedule:
    - cron: '0 0 * * *' # Executa diariamente (à meia-noite UTC)
  workflow_dispatch: # Permite execução manual do workflow

jobs:
  check-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch latest release
        id: fetch_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/jitsi/jitsi-meet/releases | jq -r '.[0].tag_name')
          echo "Latest release: $latest_release"
          echo "::set-output name=latest_release::$latest_release"

      - name: Notify via GitHub
        if: always()
        run: |
          echo "The latest release is ${{ steps.fetch_release.outputs.latest_release }}."
